{
  "text": "2024-04-08 13:19:12.151 | ERROR    | app.utils.handlers.errors.error_handler:handle_unexpected_error:24 - {'url': 'http://172.18.0.4:8080/sendmail/fhlfbasdfbakjdbfsdlkfsdkjdlfsjdf/details/sb+dakjskbkjsabdsakjbsald', 'method': 'GET', 'data': b'', 'request': None, 'traceback': 'Traceback (most recent call last):\\n  File \"/var/lang/lib/python3.10/site-packages/flask/app.py\", line 1823, in full_dispatch_request\\n    rv = self.dispatch_request()\\n  File \"/var/lang/lib/python3.10/site-packages/flask/app.py\", line 1799, in dispatch_request\\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\\n  File \"/var/lang/lib/python3.10/site-packages/connexion/decorators/decorator.py\", line 68, in wrapper\\n    response = function(request)\\n  File \"/var/lang/lib/python3.10/site-packages/connexion/decorators/uri_parsing.py\", line 149, in wrapper\\n    response = function(request)\\n  File \"/var/lang/lib/python3.10/site-packages/connexion/decorators/validation.py\", line 399, in wrapper\\n    return function(request)\\n  File \"/var/lang/lib/python3.10/site-packages/connexion/decorators/parameter.py\", line 120, in wrapper\\n    return function(**kwargs)\\n  File \"/usr/src/app/app/utils/logging/decorator.py\", line 11, in wrapper\\n    return func(*args, **kwargs)\\nTypeError: partner_id_get_email() got an unexpected keyword argument \\'partner_id\\'\\n'}\n",
  "record": {
    "elapsed": { "repr": "0:00:02.882096", "seconds": 2.882096 },
    "exception": null,
    "extra": {},
    "file": {
      "name": "error_handler.py",
      "path": "/usr/src/app/app/utils/handlers/errors/error_handler.py"
    },
    "function": "handle_unexpected_error",
    "level": { "icon": "‚ùå", "name": "ERROR", "no": 40 },
    "line": 24,
    "message": "{'url': 'http://172.18.0.4:8080/sendmail/fhlfbasdfbakjdbfsdlkfsdkjdlfsjdf/details/sb+dakjskbkjsabdsakjbsald', 'method': 'GET', 'data': b'', 'request': None, 'traceback': 'Traceback (most recent call last):\\n  File \"/var/lang/lib/python3.10/site-packages/flask/app.py\", line 1823, in full_dispatch_request\\n    rv = self.dispatch_request()\\n  File \"/var/lang/lib/python3.10/site-packages/flask/app.py\", line 1799, in dispatch_request\\n    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)\\n  File \"/var/lang/lib/python3.10/site-packages/connexion/decorators/decorator.py\", line 68, in wrapper\\n    response = function(request)\\n  File \"/var/lang/lib/python3.10/site-packages/connexion/decorators/uri_parsing.py\", line 149, in wrapper\\n    response = function(request)\\n  File \"/var/lang/lib/python3.10/site-packages/connexion/decorators/validation.py\", line 399, in wrapper\\n    return function(request)\\n  File \"/var/lang/lib/python3.10/site-packages/connexion/decorators/parameter.py\", line 120, in wrapper\\n    return function(**kwargs)\\n  File \"/usr/src/app/app/utils/logging/decorator.py\", line 11, in wrapper\\n    return func(*args, **kwargs)\\nTypeError: partner_id_get_email() got an unexpected keyword argument \\'partner_id\\'\\n'}",
    "module": "error_handler",
    "name": "app.utils.handlers.errors.error_handler",
    "process": { "id": 254, "name": "MainProcess" },
    "thread": {
      "id": 140403398686464,
      "name": "Thread-2 (process_request_thread)"
    },
    "time": {
      "repr": "2024-04-08 13:19:12.151720+00:00",
      "timestamp": 1712582352.15172
    }
  }
}
